# Generated by Django 5.0.4 on 2024-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped/Dispatched', 'Shipped/Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Returned', 'Returned'), ('On Hold', 'On Hold'), ('Backordered', 'Backordered'), ('Partially Shipped', 'Partially Shipped'), ('Awaiting Payment', 'Awaiting Payment'), ('Awaiting Fulfillment', 'Awaiting Fulfillment')], default='Pending', max_length=20),
        ),
    ]
