# Generated by Django 5.0.4 on 2024-04-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eapp.product',),
        ),
    ]
