# Generated by Django 5.0.4 on 2024-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_alter_customer_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recepient_contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
