# Generated by Django 5.0.4 on 2024-04-19 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_alter_address_recepient_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recepient_contact',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
