# Generated by Django 5.0.4 on 2024-05-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_alter_customer_contact_number_alter_seller_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAmount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('PurchaseOrderDate', models.DateField()),
                ('Status', models.CharField(max_length=250)),
                ('ExpectedDeliveryDate', models.DateField()),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('PurchaseUnitPrice', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.product')),
                ('PurchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.purchaseorder')),
            ],
        ),
    ]
