# Generated by Django 5.0.4 on 2024-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0012_product_cost_product_sku_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
