# Generated by Django 5.0.4 on 2024-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0013_adminmessage_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='TotalAmount',
        ),
    ]
