# Generated by Django 5.0.4 on 2024-05-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0016_seller_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMessage',
            new_name='POMessage',
        ),
    ]
