# Generated by Django 5.0.4 on 2024-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0017_rename_adminmessage_pomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_message',
            field=models.TextField(blank=True),
        ),
    ]
